apiVersion: skaffold/v2beta29	# 	version of the configuration.
kind: Config
metadata:
  name: alice
build:
  artifacts:
  - image: eightballer/django_backend
    context: services/backend
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: dashy
        namespace: dashy
        createNamespace: true
        chartPath: charts/dashy
        valuesFiles:
          - configs/local/values/dashy.yaml



portForward:
  - resourceType: service
    resourceName: dashy
    port: 80
    localPort: 8080
