apiVersion: skaffold/v2beta29	# 	version of the configuration.
kind: Config
metadata:
  name: alice
build:
  artifacts:
  - image: eightballer/django_backend
    context: services/backend
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: dashy
        namespace: dashy
        createNamespace: true
        chartPath: charts/dashy
        valuesFiles:
          - configs/local/values/dashy.yaml
      # webapp deployment
      - name: webapp
        namespace: webapp
        createNamespace: true
        chartPath: charts/webapp
        valuesFiles:
        - configs/local/values/webapp.yaml
        artifactOverrides:
          image: eightballer/django_backend
        imageStrategy:
          helm: {}

portForward:
  - resourceType: service
    resourceName: dashy
    namespace: dashy
    port: 80
    localPort: 8080

  - resourceType: service
    resourceName: webapp
    namespace: webapp
    port: 80
    localPort: 8085
