# Generated by Django 4.2 on 2023-04-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0002_provision_initial_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commit",
            old_name="hash",
            new_name="sha",
        ),
    ]
