# Generated by Django 4.2 on 2023-04-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0008_add_tempory_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="repos.organisation",
                null=True
            ),
            preserve_default=False,
        ),
    ]
