# Generated by Django 4.2 on 2023-04-12 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0009_role_organisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="organisation",
        ),
    ]
