# Generated by Django 4.2 on 2023-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0012_honors_institution_alter_education_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="degree",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
