# Generated by Django 4.2 on 2023-04-14 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("repos", "0013_education_degree"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Honors",
            new_name="Honor",
        ),
    ]
